spring:
  flyway:
    url: jdbc:h2:mem:insurance_db;DB_CLOSE_DELAY=-1
    user: sa
    enabled: true
    password:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:insurance_db;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
server:
  port: 8100
  address: 0.0.0.0
  servlet:
    context-path: /insurance

