-- Cars

INSERT INTO PUBLIC.CARS (MODEL, MANUFACTURER, "YEAR", FIPE_VALUE)
VALUES ('Civic Sedan SPORT 2.0 Flex 16V Aut.4p', 'Honda', '2021', 118319);

INSERT INTO PUBLIC.CARS (MODEL, MANUFACTURER, "YEAR", FIPE_VALUE)
VALUES ('ASX 2.0 16V 4x2 Flex Aut.', 'Mitsubishi', '2019 ', 95957);

INSERT INTO PUBLIC.CARS (MODEL, MANUFACTURER, "YEAR", FIPE_VALUE)
VALUES ('Baleno Wagon 1.6 16V Aut.', 'Suzuki', '2000 ', 10244);

INSERT INTO PUBLIC.CARS (MODEL, MANUFACTURER, "YEAR", FIPE_VALUE)
VALUES ('Hilux Chassi 4x4 2.8 TDI Diesel Mec.', 'Toyota', '2023 ', 203281);

INSERT INTO PUBLIC.CARS (MODEL, MANUFACTURER, "YEAR", FIPE_VALUE)
VALUES ('Forester 2.0 16v 4x4 Turbo Aut.', 'Subaru', '2005 ', 29968);

-- Drivers

INSERT INTO PUBLIC.DRIVERS (DOCUMENT, BIRTHDATE)
VALUES ('19019464640', '1980-10-20');

INSERT INTO PUBLIC.DRIVERS (DOCUMENT, BIRTHDATE)
VALUES ('45341814707', '1990-10-20');

INSERT INTO PUBLIC.DRIVERS (DOCUMENT, BIRTHDATE)
VALUES ('05486632622', '2001-01-20');

INSERT INTO PUBLIC.DRIVERS (DOCUMENT, BIRTHDATE)
VALUES ('19421837503', '2003-05-31');

INSERT INTO PUBLIC.DRIVERS (DOCUMENT, BIRTHDATE)
VALUES ('29004660098', '1999-12-25');

-- Customers

INSERT INTO PUBLIC.CUSTOMER (NAME, DRIVER_ID)
VALUES ('Puba Beariopen Blute', 1);

INSERT INTO PUBLIC.CUSTOMER (NAME, DRIVER_ID)
VALUES ('Wuldbrokie Syul', 2);

INSERT INTO PUBLIC.CUSTOMER (NAME, DRIVER_ID)
VALUES ('Lihamph Ishug', 3);

INSERT INTO PUBLIC.CUSTOMER (NAME, DRIVER_ID)
VALUES ('Fueas Pokos', 4);

INSERT INTO PUBLIC.CUSTOMER (NAME, DRIVER_ID)
VALUES ('Waesga Venyucli', 5);

-- Car Drivers

INSERT INTO PUBLIC.CAR_DRIVERS (CAR_ID, DRIVER_ID, IS_MAIN_DRIVER)
VALUES (1, 1, true);

INSERT INTO PUBLIC.CAR_DRIVERS (CAR_ID, DRIVER_ID, IS_MAIN_DRIVER)
VALUES (1, 2, false);

INSERT INTO PUBLIC.CAR_DRIVERS (CAR_ID, DRIVER_ID, IS_MAIN_DRIVER)
VALUES (2, 4, true);

INSERT INTO PUBLIC.CAR_DRIVERS (CAR_ID, DRIVER_ID, IS_MAIN_DRIVER)
VALUES (2, 3, false);

INSERT INTO PUBLIC.CAR_DRIVERS (CAR_ID, DRIVER_ID, IS_MAIN_DRIVER)

-- Claims

INSERT INTO PUBLIC.CLAIMS (CAR_ID, DRIVER_ID, EVENT_DATE)
VALUES (1, 1, '2023-10-12');

INSERT INTO PUBLIC.CLAIMS (CAR_ID, DRIVER_ID, EVENT_DATE)
VALUES (1, 2, '2023-07-04');

INSERT INTO PUBLIC.CLAIMS (CAR_ID, DRIVER_ID, EVENT_DATE)
VALUES (1, 1, '2023-08-02');

INSERT INTO PUBLIC.CLAIMS (CAR_ID, DRIVER_ID, EVENT_DATE)
VALUES (2, 4, '2023-06-14');

INSERT INTO PUBLIC.CLAIMS (CAR_ID, DRIVER_ID, EVENT_DATE)
VALUES (2, 3, '2023-02-07');

INSERT INTO PUBLIC.CLAIMS (CAR_ID, DRIVER_ID, EVENT_DATE)
VALUES (3, 5, '2023-01-24');

